import { Song, Artist, Playlist, UserProfile } from '../types/music';

export const MOCK_USER: UserProfile = {
  name: 'Alex Rivers',
  username: '@arivers',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  stats: {
    playedCount: '1.2k',
    artistsCount: 45,
    playlistsCount: 6,
  },
};

export const INITIAL_SONGS: Song[] = [
  {
    id: 's1',
    title: 'Midnight City',
    artist: 'M83',
    duration: '4:03',
    durationSeconds: 243,
    cover: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=400&auto=format&fit=crop&q=80',
    isFavorite: true,
    album: 'Hurry Up, We\'re Dreaming',
    genre: 'Synthwave',
    plays: 4200,
  },
  {
    id: 's2',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    duration: '3:20',
    durationSeconds: 200,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80',
    isFavorite: true,
    album: 'After Hours',
    genre: 'Synthpop',
    plays: 8900,
  },
  {
    id: 's3',
    title: 'Starboy',
    artist: 'The Weeknd',
    duration: '3:50',
    durationSeconds: 230,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80',
    isFavorite: false,
    album: 'Starboy',
    genre: 'R&B / Pop',
    plays: 6500,
  },
  {
    id: 's4',
    title: 'Neon Nights',
    artist: 'Cyber Pulse',
    duration: '3:45',
    durationSeconds: 225,
    cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
    isFavorite: true,
    album: 'Retrofuturism',
    genre: 'Synthwave',
    plays: 3100,
  },
  {
    id: 's5',
    title: 'Deep Focus Flow',
    artist: 'Lo-Fi Roots',
    duration: '2:40',
    durationSeconds: 160,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80',
    isFavorite: false,
    album: 'Study Sessions Vol. 1',
    genre: 'Lo-Fi',
    plays: 5200,
  },
  {
    id: 's6',
    title: 'Lunar Echoes',
    artist: 'The Midnight Riders',
    duration: '4:15',
    durationSeconds: 255,
    cover: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&auto=format&fit=crop&q=80',
    isFavorite: true,
    album: 'Nocturnal Sky',
    genre: 'Indie Rock',
    plays: 2800,
  },
  {
    id: 's7',
    title: 'Summer Horizon',
    artist: 'Luna Eclipse',
    duration: '3:10',
    durationSeconds: 190,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80',
    isFavorite: false,
    album: 'Golden Hour',
    genre: 'Indie Pop',
    plays: 1900,
  },
  {
    id: 's8',
    title: 'Frequency Shift',
    artist: 'Audio Kinetics',
    duration: '5:02',
    durationSeconds: 302,
    cover: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&auto=format&fit=crop&q=80',
    isFavorite: false,
    album: 'Sonic Waves',
    genre: 'Electronic',
    plays: 4100,
  },
];

export const INITIAL_ARTISTS: Artist[] = [
  {
    id: 'a1',
    name: 'Neon Waves',
    tracksCount: 42,
    genre: 'Synthwave',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    isFollowed: true,
    bio: 'Dúo pionero del synthwave y retrowave con sintetizadores analógicos.',
  },
  {
    id: 'a2',
    name: 'Luna Eclipse',
    tracksCount: 18,
    genre: 'Indie Pop',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    isFollowed: true,
    bio: 'Compositora e intérprete independiente con melodías envolventes.',
  },
  {
    id: 'a3',
    name: 'DJ Pulse',
    tracksCount: 104,
    genre: 'EDM / Dance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    isFollowed: true,
    bio: 'Productor internacional con sets en los festivales más importantes.',
  },
  {
    id: 'a4',
    name: 'Ether Ambient',
    tracksCount: 32,
    genre: 'Ambient',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    isFollowed: false,
    bio: 'Paisajes sonoros para concentración profunda, yoga y meditación.',
  },
  {
    id: 'a5',
    name: 'K-Flow',
    tracksCount: 56,
    genre: 'Hip Hop / Trap',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    isFollowed: true,
    bio: 'Beats urbanos con rimas afiladas y ritmos de última generación.',
  },
];

export const INITIAL_PLAYLISTS: Playlist[] = [
  {
    id: 'p1',
    title: 'Tus Me Gusta',
    description: 'Canciones que marcaste con corazón para escuchar siempre.',
    creator: 'Alex Rivers',
    tracksCount: 4,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80',
    songIds: ['s1', 's2', 's4', 's6'],
    genreTag: 'Favoritos',
    createdAt: '2026-01-10',
  },
  {
    id: 'p2',
    title: 'Night Drive Essentials',
    description: 'Sintetizadores, luces de neón y carreteras vacías a medianoche.',
    creator: 'Alex Rivers',
    tracksCount: 4,
    cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80',
    songIds: ['s1', 's2', 's4', 's8'],
    genreTag: 'Synthwave',
    createdAt: '2026-02-01',
  },
  {
    id: 'p3',
    title: 'Sunday Morning Coffee',
    description: 'Melodías acústicas y lo-fi suaves para empezar el día con calma.',
    creator: 'Alex Rivers',
    tracksCount: 3,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80',
    songIds: ['s5', 's7', 's1'],
    genreTag: 'Lo-Fi / Chill',
    createdAt: '2026-02-14',
  },
  {
    id: 'p4',
    title: 'Workout High Energy',
    description: 'Ritmos rápidos para mantener la motivación al máximo en el gym.',
    creator: 'Alex Rivers',
    tracksCount: 3,
    cover: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&auto=format&fit=crop&q=80',
    songIds: ['s2', 's3', 's8'],
    genreTag: 'EDM / Dance',
    createdAt: '2026-03-01',
  },
];
